### ISSUE TITLE
Danbooru API implementation is not working

### ISSUE THREAD

**Issue by xXLINK1123Xx** [ajiiisai/booru-rs#2]
When I try to do any kind of request to danbooru API I get an 403 error. After some investigation I discovered that it happens because Cloudflare has started serving up an anti-bot challenge page which obviously blocks programmatic API access. Can you implement solution for this problem?

**Comment by xXLINK1123Xx** [comment]
Here is more info on this topic https://danbooru.donmai.us/forum_topics/22822

**Comment by ajiiisai** [comment]
I'm aware of this problem and I'm working on it. Thanks for letting me know.
