### ISSUE TITLE
DanbooruPost model has invalid type for some fields

### ISSUE THREAD

**Issue by xXLINK1123Xx** [ajiiisai/booru-rs#5]
up_score, down_score, score may contain negative values

**Comment by ajiiisai** [comment]
Thanks, it should be easy to fix. I'll take a look when I have some time.

**Comment by ajiiisai** [comment]
Fixed on https://github.com/ajiiisai/booru-rs/commit/bf13e4fe437eadd9e8cc5ed13bd4d011d7e45bdc
