### ISSUE TITLE
use rustls for reqwest instead of native TLS

### ISSUE THREAD

**Issue by Scraft161** [ajiiisai/booru-rs#9]
Reqwest is the only dependency to use the system's TLS which can be a problem when doing cross-compilation as it is dynamically linked.

This issue can be resolved however by changing the following line in the `Cargo.toml`
```toml
reqwest = { version = "0.11.12", features = ["json"] }
```
to
```toml
reqwest = { version = "0.11.12", features = ["json", "rustls-tls"], default-features = false }
```

Doing this solved my issue as reqwest is the only library still not to use rustls by default in my project, although I would highly recommend you look through the other default features to see which ones you do need.

This change doesn't change any of the functionality your library is currently using so it'd be great to either have this by default or behind a feature flag people can enable.

**Comment by ajiiisai** [comment]
I'm going to use this suggestion for now. Probably a feature toggle would be better in the future so I'll keep it in mind.
Thanks for the heads up!

**Comment by Scraft161** [comment]
alright, I have the changes pushed to [my own fork](https://github.com/Scraft161/booru-rs) for anyone who needs it.
in reality it's just a single line change that can be pulled in or applied as a patch to future versions of this project.

I'm not planning on actively maintaining it; since this change is trivial at best but anyone who wishes to make this a proper PR may do so at any point.

**Comment by ajiiisai** [comment]
Already submitted the changes myself earlier with the pertinent update to the crates.io library ^^
